### PR TITLE
chore(deps): Update to include ngx-bootstrap v8 as an engine requirement

### PR DESCRIPTION
**Pull request by jethas-bennettjones**

### CODE REVIEW

**Comment by jethas-bennettjones** [comment]
FYI @Gillardo

**Comment by Gillardo** [comment]
i will look at this later today for you

**Comment by Gillardo** [comment]
should now be published to npm as well on version 7.0.3

**Comment by jethas-bennettjones** [comment]
Hi @Gillardo.

Thanks for this, but it looks like the team renamed DatepickerModule to BsDatePickerModule in v8 of ngx-bootstrap. Now it won't compile at all.

This is the error I get:
```
Error: node_modules/ngx-bootstrap-datetime-popup/lib/ngx-bootstrap-datetime-popup.module.d.ts:11:187 - error TS2551: Property 'DatepickerModule' does not exist on type 'typeof import("ngx-bootstrap/datepicker")'.
Did you mean 'BsDatepickerModule'?

11     static ɵmod: i0.ɵɵNgModuleDeclaration<DatetimePopupModule, [typeof i1.DatetimePopupComponent, typeof i2.OffClickDirective], [typeof i3.CommonModule, typeof i4.FormsModule, typeof i5.DatepickerModule, typeof
 i6.TimepickerModule, typeof i5.BsDatepickerModule, typeof i7.BsDropdownModule], [typeof i1.DatetimePopupComponent]>;
                                                                                                                                                                                             ~~~~~~~~~~~~~~~~

    at addError (E:\dev\code\components\node_modules\@ngtools\webpack\src\ivy\diagnostics.js:31:29)
    at E:\dev\code\components\node_modules\@ngtools\webpack\src\ivy\diagnostics.js:17:17
    at AngularWebpackPlugin.updateJitProgram (E:\dev\code\components\node_modules\@ngtools\webpack\src\ivy\plugin.js:479:9)
    at E:\dev\code\components\node_modules\@ngtools\webpack\src\ivy\plugin.js:199:24
    at Hook.eval [as call] (eval at create (E:\dev\code\components\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:19:1)
    at Hook.CALL_DELEGATE [as _call] (E:\dev\code\components\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (E:\dev\code\components\node_modules\webpack\lib\Compiler.js:1108:30)
    at E:\dev\code\components\node_modules\webpack\lib\Compiler.js:1153:29
    at _next0 (eval at create (E:\dev\code\components\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
    at eval (eval at create (E:\dev\code\components\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:55:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jethas-bennettjones** [comment]
Thanks for the clarification, @Gillardo. Apologies for bringing this up.

**Comment by Gillardo** [comment]
i have removed v8 for the moment as not got time to go through it, latest release 7.0.4.

If you want to do a PR, please do one and check it builds using the `npm run build` command

**Pull request merged**
