### PR TITLE
Angular 13

### PR DESCRIPTION
**Pull request by jethas-bennettjones**
feat: Upgrade to Angular 13. Also fix build and serve issues.

### CODE REVIEW

**Comment by jethas-bennettjones** [comment]
@Gillardo

**Comment by Gillardo** [comment]
Thanks for the PR

**Comment by jethas-bennettjones** [comment]
@Gillardo Just out of curiosity, when do you think a new version will be pushed out to npm?

**Comment by Gillardo** [comment]
Even though this has been merged, it seems to have broken the dist as package.json is pointing to files that dont exist now

**Pull request merged**
