### PR TITLE
ng aot build fixes

### PR DESCRIPTION
**Pull request by sn123**
Doing ng build --prod fails and clicking on button in a form causes it to submit

### CODE REVIEW

**Comment by sn123** [comment]
could you please push a new npm version? Current one is not usable with aot builds, thanks!

**Comment by Gillardo** [comment]
Give me a sec

**Comment by Gillardo** [comment]
I have now released and published version 1.2.4.  Hope this is ok

**Comment by sn123** [comment]
1.2.4 works like a charm, thanks!

**Comment by Gillardo** [comment]
Np, thanks for PR

**Comment by sn123** [comment]
Hey, there's still issue with AOT builds. Even though the aot build compiles fine now, If I run the app, I get "x" is not a constructor. I only get this error if I include the npm package, if I directly copy over the source files and include the module within the app itself, I don't get this error with aot runs.

**Comment by Gillardo** [comment]
your using `angular-cli` and the `ng build` command?

**Comment by sn123** [comment]
Yes using cli and ng build –-prod which triggers an AOT build.

**Comment by Gillardo** [comment]
i have now converted my own site to use angular-cli.  I will try and do a build shortly and see if i get the issue

**Comment by sn123** [comment]
Sure thanks, I guess there’s an issue with metadata file generated for npm since including source works fine.

________________________________

**Comment by Gillardo** [comment]
can you download 1.2.6 and try it?  I have now moved to angular-cli and experienced the same problem.  I have rebuilt the datetime library and then copied the code into my project locally and it worked.  So if you can download it via npm, you should now not get the same problem

**Comment by Gillardo** [comment]
make that 1.2.7.  I have tried it from npm and all working!!

**Comment by sn123** [comment]
Thanks, sorry haven’t been near my system today. Will confirm tomorrow and let you know. By the way, what was the issue?

**Comment by Gillardo** [comment]
you can now use the component via npm and it wont error when using --aot

**Pull request merged**
